name: Build and Push Docker Image

on:
  push:
    branches:
      - feature/docker-build  # 在推送到feature/docker-build分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # DockerHub的用户名
          password: ${{ secrets.DOCKER_PASSWORD }} # DockerHub的密码

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sguann/videolingo_app:latest  # DockerHub的仓库
